# Generated by Django 3.1.2 on 2020-10-09 13:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TwilioNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "lastModified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificacao"
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isPublic", models.BooleanField(default=False)),
                (
                    "number",
                    models.CharField(
                        default="twilionumer",
                        max_length=32,
                        verbose_name="Twilio number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twilio number",
                "verbose_name_plural": "Twillio Numbers",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TwilioSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "lastModified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificacao"
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isPublic", models.BooleanField(default=False)),
                (
                    "accountSID",
                    models.CharField(
                        default="TwilioaccountSID",
                        max_length=256,
                        verbose_name="account SID",
                    ),
                ),
                (
                    "accountToken",
                    models.CharField(
                        default="accountToken",
                        max_length=256,
                        verbose_name="account Token",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twilio Setting",
                "verbose_name_plural": "Twilio Settings",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TwilioSMS",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "lastModified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificacao"
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isPublic", models.BooleanField(default=False)),
                (
                    "smsTo",
                    models.CharField(
                        default="Gateway Name",
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Please check the number",
                                regex=re.compile("^\\+[1-9]\\d{1,14}$"),
                            )
                        ],
                        verbose_name="Server name",
                    ),
                ),
                (
                    "smsMessage",
                    models.CharField(
                        default="Gateway Name",
                        max_length=256,
                        verbose_name="Server name",
                    ),
                ),
                (
                    "smsFrom",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="twiliosms.twilionumber",
                        verbose_name="Twillio Number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twillio SMS ",
                "verbose_name_plural": "Twillio SMSs",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="twiliosettings",
            index=models.Index(
                fields=["-created"], name="twiliosms_t_created_8410a3_idx"
            ),
        ),
        migrations.AddField(
            model_name="twilionumber",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Number Owner",
            ),
        ),
        migrations.AddField(
            model_name="twilionumber",
            name="twilioSettings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="twiliosms.twiliosettings",
                verbose_name="Twilio Settings",
            ),
        ),
        migrations.AddIndex(
            model_name="twiliosms",
            index=models.Index(
                fields=["-created"], name="twiliosms_t_created_f76772_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="twilionumber",
            index=models.Index(
                fields=["-created"], name="twiliosms_t_created_7cedf2_idx"
            ),
        ),
    ]
